# Travis configuration for open311-android-fundi
language: android
sudo: false
android:
  components:
    - tools
    - platform-tools
    - tools

    # build tools used for the project
    - build-tools-26.0.2
    - extra-google-m2repository
    - extra-google-android-support
    - extra-android-m2repository

    # SDK version used to compile the project
    - android-22
    - android-25

  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'



# add java 8 supports
jdk: oraclejdk8

os:
  - linux

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - chmod +x gradlew


# safelist branches which will be built
branches:
  only:
    - develop


script:
  # Run automated Test
    - ./gradlew test


# prevent travis dependency caching
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache